#########################################
# NSI-DDS test configuration.           #
#########################################
version: '3.8'
services:
  db-east:
    image: postgres:14.1-alpine
    container_name: db-east
    restart: always
    environment:
      - POSTGRES_USER=opennsa
      - POSTGRES_PASSWORD=opennsa
      - POSTGRES_DB=opennsa
    ports:
      - '5432:5432'
    volumes: 
      - ./compose/02-schema.sql:/docker-entrypoint-initdb.d/02-schema.sql:ro
      - db-east:/var/lib/postgresql/data

  opennsa-east:
    image: opennsa:latest
    container_name: opennsa-east
    build:
      context: github.com/jmacauley/opennsa
      dockerfile: docker/Dockerfile
    env_file: compose/opennsa-east-config/opennsa.env
    depends_on:
      - db-east
    ports:
      - '9080:9080'
    volumes:
      - ./compose/opennsa-east-config/opennsa.conf:/home/opennsa/opennsa/config/opennsa.conf:ro
      - ./compose/opennsa-east-config/opennsa.nrm:/home/opennsa/opennsa/config/opennsa.nrm:ro

  nsi-dds-east:
    image: nsi-dds:latest
    container_name: nsi-dds-east
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: 1
    depends_on:
      - opennsa-east
    ports:
      - '8401:8401'
    volumes:
      - ./compose/nsi-dds-east-config:/nsi-dds/config
      - /tmp:/nsi-dds/var/log

  db-west:
    image: postgres:14.1-alpine
    container_name: db-west
    restart: always
    environment:
      - POSTGRES_USER=opennsa
      - POSTGRES_PASSWORD=opennsa
      - POSTGRES_DB=opennsa
    ports:
      - '5433:5432'
    volumes:
      - ./compose/02-schema.sql:/docker-entrypoint-initdb.d/02-schema.sql:ro
      - db-west:/var/lib/postgresql/data

  opennsa-west:
    image: opennsa:latest
    container_name: opennsa-west
    build:
      context: github.com/jmacauley/opennsa
      dockerfile: docker/Dockerfile
    env_file: compose/opennsa-west-config/opennsa.env
    depends_on:
      - db-west
    ports:
      - '9081:9080'
    volumes:
      - ./compose/opennsa-west-config/opennsa.conf:/home/opennsa/opennsa/config/opennsa.conf:ro
      - ./compose/opennsa-west-config/opennsa.nrm:/home/opennsa/opennsa/config/opennsa.nrm:ro

  nsi-dds-west:
    image: nsi-dds:latest
    container_name: nsi-dds-west
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: 1
    depends_on:
      - db-west
    ports:
      - '8402:8401'
    volumes:
      - ./compose/nsi-dds-west-config:/nsi-dds/config
      - /tmp:/nsi-dds/var/log

volumes:
  db-east:
    driver: local
  db-west:
    driver: local
