apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nsi-dds.fullname" . }}-{{ .Values.cache.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cache.storage }}
