apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nsi-dds.fullname" . }}
  labels:
    {{- include "nsi-dds.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Chart.Name }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "nsi-dds.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        automation.surf.net/config-checksum: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nsi-dds.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nsi-dds.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.config.caSecretName }}
      initContainers:
        - name: ca-to-truststore
          securityContext:
            runAsUser: 0
          image: debian:trixie-slim
          command:
            - sh
            - -c
            - |
              cd /truststore
              cp /ca/ca.crt .
              apt-get update
              apt-get install -y --no-install-recommends openjdk-21-jdk-headless
              awk '/-----BEGIN CERTIFICATE-----/ {out="cert" ++i ".pem"}; out {print >> out} /-----END CERTIFICATE-----/ {out=""}' ca.crt
              for cert in cert*.pem; do
                  cn=$(openssl x509 -in ${cert} -noout -subject | sed -n 's/^subject=//p')
                  echo "${cn}"
                  keytool -trustcacerts -storepass secret -importcert -alias "${cn}" -file ${cert} -keystore nsi-dds-truststore.jks -noprompt
              done
              rm cert*.pem
          volumeMounts:
            - name: truststore
              mountPath: /truststore
            - name: ca
              mountPath: /ca
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["java"]
          args: ["-Xmx1536m", 
                 "-Djava.net.preferIPv4Stack=true",
                 "-Dcom.sun.xml.bind.v2.runtime.JAXBContextImpl.fastBoot=true",
                 {{ printf "-Djava.util.logging.config.file=%s/logging.properties" .Values.config.mountPath | quote }},
                 {{ printf "-Dlogback.configurationFile=%s/logback.xml" .Values.config.mountPath | quote }},
                 {{ printf "-Dbasedir=%s" .Values.image.home | quote }},
                 "-jar", {{ printf "%s/dds.jar" .Values.image.home | quote }},
                 "-ddsConfigFile", {{ printf "%s/dds.xml" .Values.config.mountPath | quote }}]
          volumeMounts:
            - name: cache
              mountPath: {{ .Values.cache.mountPath }}
            - name: config
              mountPath: {{ .Values.config.mountPath }}
              readOnly: true
          {{- if (((.Values.config).keystore).secretName) }}
            - name: keystore
              mountPath: "{{ .Values.config.mountPath }}/key"
              readOnly: true
          {{- end }}
          {{- if (((.Values.config).truststore).secretName) }}
            - name: truststore
              mountPath: "{{ .Values.config.mountPath }}/trust"
              readOnly: true
          {{- end }}
          {{- if .Values.config.caSecretName }}
            - name: truststore
              mountPath: /truststore
          {{- end }}
          ports:
            - name: internal
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              scheme: {{ .Values.livenessProbe.scheme }}
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.service.containerPort }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              scheme: {{ .Values.startupProbe.scheme }}
              path: {{ .Values.startupProbe.path }}
              port: {{ .Values.service.containerPort }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: config
          configMap:
            {{- if .Values.config.configMapName }}
            name: {{ .Values.config.configMapName }}
            {{- else }}
            name: {{ .Release.Name }}-config
            {{- end }}
            items:
            - key: "dds.xml"
              path: "dds.xml"
            - key: "logging.properties"
              path: "logging.properties"
            - key: "log4j.xml"
              path: "log4j.xml"
            {{- if (((.Values.config).keystore).secretName) }}
            {{- else }}
            - key: "nsi-dds-keystore.jks"
              path: "key/nsi-dds-keystore.jks"
            {{- end }}
            {{- if or (((.Values.config).truststore).secretName) ((.Values.config).caSecretName) }}
            {{- else }}
            - key: "nsi-dds-truststore.jks"
              path: "trust/nsi-dds-truststore.jks"
            {{- end }}
        {{- if (((.Values.config).keystore).secretName) }}
        - name: keystore
          secret:
            secretName: {{ .Values.config.keystore.secretName }}
            items:
            - key: {{ .Values.config.keystore.key }}
              path: nsi-dds-keystore.jks
        {{- end }}
        {{- if (((.Values.config).truststore).secretName) }}
        - name: truststore
          secret:
            secretName: {{ .Values.config.truststore.secretName }}
            items:
            - key: {{ .Values.config.truststore.key }}
              path: nsi-dds-truststore.jks
        {{- end }}
        {{- if .Values.config.caSecretName }}
        - name: ca
          secret:
            secretName: {{ .Values.config.caSecretName }}
        - name: truststore
          emptyDir: {}
        {{- end }}
        - name: cache
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-cache
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
